version: "3.7"
services:
  app:
    container_name: autogpt
    hostname: autogpt
    restart: on-failure
    init: true
    stop_grace_period: 1m
    tty: true
    networks:
      - autogpt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/workspace/:/app/auto_gpt_workspace/
      - ${PWD}/logs/:/logs/
      - type: bind
        source: ${PWD}/.env
        target: /app/.env
        read_only: true 
      - type: bind
        source: ${PWD}/ai_settings.yaml
        target: /app/ai_settings.yaml
        read_only: false
      - type: bind
        source: ${PWD}/auto-gpt.json
        target: /app/auto-gpt.json
        read_only: false
    depends_on:
      - cache
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_1_ID=${ELEVENLABS_VOICE_1_ID}
      - ELEVENLABS_VOICE_2_ID=${ELEVENLABS_VOICE_2_ID}
      - SMART_LLM_MODEL=${SMART_LLM_MODEL}
      - FAST_LLM_MODEL=${FAST_LLM_MODEL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CUSTOM_SEARCH_ENGINE_ID=${CUSTOM_SEARCH_ENGINE_ID}
      - USE_AZURE=${USE_AZURE}
      - OPENAI_AZURE_API_BASE=${OPENAI_AZURE_API_BASE}
      - OPENAI_AZURE_API_VERSION=${OPENAI_AZURE_API_VERSION}
      - OPENAI_AZURE_DEPLOYMENT_ID=${OPENAI_AZURE_DEPLOYMENT_ID}
      - IMAGE_PROVIDER=${IMAGE_PROVIDER}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - USE_MAC_OS_TTS=${USE_MAC_OS_TTS}
      - MEMORY_BACKEND=${MEMORY_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WIPE_REDIS_ON_START=${WIPE_REDIS_ON_START}
      - UID=${UID}
      - GID=${GID}
    ports:
      - 8080:8080
    command: ["gotty", "--port", "8080", "--permit-write", "--title-format", "AutoGPT Terminal", "bash", "-c", "python scripts/main.py ${COMMAND_LINE_PARAMS}"]
      # [--continuous] [--speak] [--debug] [--gpt3only] [--gpt4only] [--use-memory MEMORY_TYPE]
  cache:
    image: redis/redis-stack-server:latest
    container_name: redis
    hostname: redis
    networks:
      - autogpt
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --protected-mode no
    volumes: 
      - cache:/data
networks:
  autogpt:
volumes:
  cache:
    driver: local
