name: 'AFAAS Changelog CI v2'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11 # Specify your Python version here

        - name: Install Dependencies
          run: |
            poetry install

        - name: Run isort
          run: |
            poetry run isort --profile black .
            git config --global user.name 'isort-bot'
            git config --global user.email '

        - name: Run autopep8
          run: |
            poetry run autopep8 --in-place --recursive .

        - name: Run black
          run: |
            poetry run black .
          
        - name: Run autoflake
          run: |
            poetry run autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive .
            git config --global user.name 'autoflake-bot'
            git config --global user.email 'autoflake-bot@example.com'
            git add -A
            git commit -m "Apply autoflake fixes" || echo "No changes to commit"
            git push origin HEAD:${{ github.ref }}

        - name: "Build Changelog"
          uses: mikepenz/release-changelog-builder-action@v4.1.0
          with:
            configurationJson: |
                {
                "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
                "pr_template": "[#{{NUMBER}}](#{{URL}}) - #{{TITLE}} - [@#{{AUTHOR}}](https://github.com/#{{AUTHOR}})
                ) , #{{LABELS}} \n",
                "categories": [
                    {
                        "title": "## ðŸ’¬ Other",
                        "labels": ["other"]
                    },
                    {
                        "title": "## ðŸ“¦ Dependencies",
                        "labels": ["dependencies"]
                    }
                ],
                "custom_placeholders": [
                  {
                    "name": "SMILEY",
                    "source": "LABELS",
                    "transformer": {
                      "pattern": "[\\S\\s]*?(https:\\/\\/corp\\.atlassian\\.net\\/browse\\/LABELS-.{2,4})[\\S\\s]*",
                      "target": "- $1"
                    }
                  }
                ]
                }
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}