name: Update Changelog and Readme

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Merged PRs and Update Docs
        id: fetch-merged-prs  # Assign an ID to this step
        uses: actions/github-script@v7
        with:
          script: |
            const yesterday = new Date();
            yesterday.setDate(yesterday.getDate() - 1);
            const formattedDate = yesterday.toISOString().split('T')[0];

            const query = `repo:${context.repo.owner}/${context.repo.repo} is:pr is:merged merged:>=${formattedDate}`;
            const prs = await github.rest.search.issuesAndPullRequests({ q: query });

            let docsContent = '';
            for (const pr of prs.data.items) {
              const prDate = new Date(pr.merged_at).toISOString().split('T')[0];
              docsContent += `${prDate} - [PR #${pr.number}](${pr.html_url}) : ${pr.title} [@${pr.user.login}](${pr.user.html_url})\n`;
            }

            if (docsContent) {
              const fs = require('fs');
              // Append to CHANGELOG.md
              fs.appendFileSync('CHANGELOG.md', docsContent);
              // Append to README.md
              fs.appendFileSync('README.md', docsContent);
              core.setOutput('updated', true);
            }

      - name: Commit and push if changed
        if: steps.fetch-merged-prs.outputs.updated == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add CHANGELOG.md README.md
          git commit -m "Update documentation with recent PRs"
          git push
